### ISSUE TITLE
[Bug Report] 启动成功但是极短的时间内退出（Docker）

### ISSUE THREAD

**Issue by lingfengchencn** [MCSManager/MCSManager#1365]
### Platform

docker / centos7

### Panel Version

latest

### Daemon Version (Optional)

latest

### Recurrence Probability

100%

### Bug Description

前置指令
1、创建 docker-compose.yaml
```yaml
version: '3'

services:
  web:
    image: registry.cn-guangzhou.aliyuncs.com/kabaka/kabaka:mcsmv10_web
    container_name: mcsmv10_web
    restart: always
    network_mode: host
    environment:
      - TZ=Asia/Shanghai
    ports:
      - 4043:23333
      - 4044:24444
    volumes:
      - ./docker-mcsm/web:/opt/docker-mcsm/web/data
      - ./docker-mcsm/web/logs:/opt/docker-mcsm/web/logs
      - ./docker-mcsm/daemon/data/Config:/opt/docker-mcsm/daemon/data/Config:ro

  daemon:
    image: registry.cn-guangzhou.aliyuncs.com/kabaka/kabaka:mcsmv10_daemon
    container_name: mcsmv10_daemon
    restart: always
    network_mode: host
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./docker-mcsm/daemon/data:/opt/docker-mcsm/daemon/data
      - ./docker-mcsm/daemon/logs:/opt/docker-mcsm/daemon/logs
      - /var/run/docker.sock:/var/run/docker.sock:ro

```
2、ls `/opt/docker-mcsm/`
```sh
ln -s /data/services/docker-minecraft-bedrock-server/mcsmanager/docker-mcsm /opt/docker-mcsm
```

3、 ` docker compose up -d`

配置实力->我的世界->docker镜像
<img width="883" alt="image" src="https://github.com/user-attachments/assets/e753c2af-97df-41a0-9f88-ae3f47f335ff">
<img width="823" alt="image" src="https://github.com/user-attachments/assets/b3253a91-d17a-4403-8589-43dced4805d4">

这是为什么？我该怎么查看/调试。
