### ISSUE TITLE
[Bug Report] 容器的工作目录不应该与实例的工作目录强行一致

### ISSUE THREAD

**Issue by cglang** [MCSManager/MCSManager#1544]
### Platform

Debian，Docker

### Panel Version

10.5.0

### Recurrence Probability

100%

### Bug Description

当我将daemon和游戏服务器都托管在Docker中时，如果挂载目录与容器中的daemon工作目录不一致时，新启动的游戏服务器容器会出现错误

```yml
services:
  mcsm-daemon:
    image: githubyumao/mcsmanager-daemon:v10.5.0
    container_name: mcsmanager-daemon
    restart: always
    networks:
      - network
    ports:
      - "40000:24444"
    volumes:
      # 这里我需要统一管理容器应用产生的数据，我都放在了/data/docker目录下
      - /data/docker/mcsm/daemon:/opt/mcsmanager/daemon/data
      - /var/run/docker.sock:/var/run/docker.sock
    labels:  
      createdBy: "Apps"
networks:  
  network:  
    external: true
```

应当在下面这个位置添加容器工作目录配置，不能将实例工作目录作为容器中要用到的工作目录
![Image](https://github.com/user-attachments/assets/576efbf8-5e08-4d5f-a7e0-4c5870216e24)

**Comment by cglang** [comment]
```yml
services:
  mcsm-daemon:
    image: githubyumao/mcsmanager-daemon:v10.5.0
    container_name: mcsmanager-daemon
    restart: always
    networks:
      - network
    ports:
      - "40000:24444"
    volumes:
      - /data/docker/mcsm/daemon:/opt/mcsmanager/daemon/data
      - /data/docker/mcsm/daemon:/data/docker/mcsm/daemon
      - /var/run/docker.sock:/var/run/docker.sock
    labels:  
      createdBy: "Apps"
networks:  
  network:  
    external: true
```

额外配置`/data/docker/mcsm/daemon:/data/docker/mcsm/daemon`，将实例和容器的工作目录配成一致，倒是可以解决问题，但我总感觉这是一个BUG，或者说程序不应该这么工作。
