### ISSUE TITLE
【docker】实例启动成功立刻被关闭

### ISSUE THREAD

**Issue by lzy82546** [MCSManager/MCSManager#574]
![image](https://user-images.githubusercontent.com/65816201/154536097-aef5ecf4-33da-4833-bd73-d9e8ee0661ee.png)

win10 (21H1)
docker desktop (4.5.1)

用node镜像启动daemon和web
daemon的容器内装有docker-cli，host设置为tcp://host.docker.internal:2375操作宿主机的docker
配置守护进程和构建jdk镜像都正常
实例配置 docker模式 jdk镜像 端口25565 其他默认
控制台启动现象如上图

（太晚了长话短说，刚才写了一个小时详细步骤，一提交未响应，我tm。。明天再补充）

**Comment by OldGodShen** [comment]
MCSManager不支持Windows的docker

**Comment by lzy82546** [comment]
> MCSManager不支持Windows的docker

找到问题了，daemon执行docker run -v的挂载路径，在宿主机并不存在，指定成windows的路径就可以了
现在实现的效果是web daemon server都运行在windows docker里，也能正常玩了，但文件管理还不行，再调整一下挂载应该就可以

**Comment by lzy82546** [comment]
> > 
> 
> 如果愿意，可以在成功之后在此处反馈你的成功结论，让接下来的用户在 Windows 上也能有很好的 Docker 解决方案。
> 
> 如果收纳到文档或者 WIKI 中的话，会写上您的名字。

似乎搞定了，我正在整理，这个周末应该就可以

**Comment by lzy82546** [comment]
## 环境 ##
- Windows 10 21H1 (19043)
- Docker Desktop 4.5.1 (74721) WSL2

## 准备 ##
- BIOS 开启虚拟化
    - 微星主板：`Overclocking -> CPU 特征 -> SVM Mode` 启用
- 安装 Docker Desktop
    - 安装过程中勾选使用 `WSL2`
    - 安装完成后 `Settings -> General -> Expose daemon on tcp://localhost:2375 without TLS` 启用

## Dockerfile ##
- 可以跳过这一步直接用我构建好的镜像
- 自己构建镜像需要注意 `wget` 可能会失败，需要删除重新来
- Daemon
    ```
    FROM node:14-alpine

    RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g' /etc/apk/repositories; \
        apk add docker-cli;

    RUN cd /; \
        wget -O master.zip https://codeload.github.com/MCSManager/MCSManager-Daemon-Production/zip/refs/heads/master; \
        unzip master.zip; \
        rm master.zip; \
        mv MCSManager-Daemon-Production-master workspace; \
        cd /workspace; \
        npm install --registry=https://registry.npm.taobao.org;

    EXPOSE 24444

    WORKDIR /workspace

    CMD node app.js
    ```
- Web
    ```
    FROM node:14-alpine

    RUN cd /; \
        wget -O master.zip https://codeload.github.com/MCSManager/MCSManager-Web-Production/zip/refs/heads/master; \
        unzip master.zip; \
        rm master.zip; \
        mv MCSManager-Web-Production-master workspace; \
        cd /workspace; \
        npm install --registry=https://registry.npm.taobao.org;

    EXPOSE 23333

    WORKDIR /workspace

    CMD node app.js
    ```

## docker-compose.yml ##
```
version: "3.0"

services:
      
  daemon:
    image: registry.cn-shanghai.aliyuncs.com/lzy82546/mcsmanager-daemon:9.2.1
    container_name: mcsmanager-daemon
    restart: always
    ports:
      - 24444:24444
    volumes:
      - ${WORKSPACE}/daemon/data:/workspace/data
      - ${WORKSPACE}/daemon/logs:/workspace/logs
      - ${WORKSPACE}/server:${WORKSPACE}/server
    environment:
      TZ: Asia/Shanghai
      DOCKER_HOST: tcp://host.docker.internal:2375

  web:
    image: registry.cn-shanghai.aliyuncs.com/lzy82546/mcsmanager-web:9.2.1
    container_name: mcsmanager-web
    restart: always
    ports:
      - 23333:23333
    volumes:
      - ${WORKSPACE}/web/data:/workspace/data
      - ${WORKSPACE}/web/logs:/workspace/logs
    environment:
      TZ: Asia/Shanghai
```

## .env ##
- 指定工作目录，D:\mcsmanager 要写成下面的样子，最后不带 `/`
```
WORKSPACE=/d/mcsmanager
```

## 启动mcsmanager ##
```
docker compose up -d
```

## 配置守护进程 ##
- 浏览器访问`localhost:23333`
- 配置守护进程`host.docker.internal:24444`，秘钥在`D:\mcsmanager\daemon\data\Config\golbal.json`
- 需要外网访问就配置`{公网域名}:24444`或`{公网IP}:24444`
- Web和Daemon在同一局域网，还需要hosts中添加 `{内网IP} {公网域名}`

## 准备JAVA镜像 ##
- 我用的1.18.1官方服务端，所以是jdk17
- Dockerfile保持默认

## 创建实例 ##
- Java版 -> 单个服务端文件
- 目录留空用默认的，因为改了目录就不知道上传到哪了。。不过不重要
- 上传服务端文件（但这里上传的文件并不会被用到，主要是为了生成一条石粒记录）
- ***强烈建议把文件管理功能往外放***
- `D:\mcsmanager\daemon\server`中新建文件夹，就叫他`mc1.18.1`吧，并把服务端文件丢进去
- 实例详细信息设置
    - 工作目录：`/d/mcsmanager/daemon/server/mc1.18.1`
    - 进程启动方式：Linux Docker 容器
    - 环境镜像：刚才构建好的 `mopenjdk:17`
    - 开放端口: `25565:25565/tcp`

## 启动实例 ##
- 玩

## 其他 ##
- 主要的坑在Docker Desktop启用那个选项，可能会提示端口占用，据说是`3.5.1`版本之后的bug，2375端口被Docker Proxy占用了，照着别人的解决办法也没搞定，最后只能卸载大法，重装好Docker Desktop立刻开启这个，只要mcsmanager-daemon容器内的docker-cli能连接到外部的docker-daemon就行了
- 其次坑的是面板端拼接docker命令的自由度并不高，我只能用在容器内创建同名路径`/d/mcsmanager/daemon/server`的办法偷鸡，希望能增加一些进阶配置选项
- 网络方面因为没法用公网IP访问内网，所以我去搞了个域名，通过改host的方式，让浏览器端和面板端都能连接到守护进程端，如果配置守护进程的时候能分别配置一个内网地址、一个外网地址，能方便一点
- 公网IP访问内网，据说防火墙设置一下就行，但我没成功，**【求教】**
- 性能方面肯定不如直接在物理机上跑，具体损失多少有待测试，主要是我不喜欢电脑上有好几个命令行的黑窗口，又不会写shell脚本，人菜瘾大毛病多，正好最近因为工作原因在捣鼓Windows的Docker，然后就瞎折腾着玩的

**Comment by Suwings** [comment]
https://github.com/MCSManager/MCSManager/wiki/%E4%BD%BF%E7%94%A8-Docker-for-Windows

谢谢教程编写，已经加入到 wiki ，要是觉得自己哪里又要修改之处，请在这里重新发我一份新的即可。

**Comment by cdwcgt** [comment]
其实可以把github的镜像改为gitee的方便国内用户下载
https://gitee.com/mcsmanager/MCSManager-Daemon-Production.git
https://gitee.com/mcsmanager/MCSManager-Web-Production.git

并且其实也可以考虑安装git

镜像方面只需要在docker-compose.yml中更改volumn的设置就可以了
比如
```
volumn:
   - /Z/MCServer:/随便一个linux路径
```
然后在新建实例的时候用这个linux路径就可以了

这是我稍微调整的Dockerfile

文件树
```
│  docker-compose.yml
|   .env
│
├─daemon
│  │  Dockerfile
│  │
│  ├─data
│  │  ├─Config
│  │  │      global.json
│  │  │
│  │  ├─InstanceConfig
│  │  │
│  │  ├─InstanceData
│  │  ├─InstanceLog
│  │  │
│  │  └─TaskConfig
│  └─logs
│
└─web
    │  Dockerfile
    │
    ├─data
    │  ├─RemoteServiceConfig
    │  │
    │  ├─SystemConfig
    │  │      config.json
    │  │
    │  └─User
    │
    └─logs
```
docker-compose.yml
```
version: '3'
services:
  web:
    container_name: mcsmanager-web
    build: ./web
    ports:
      - "23333:${WEB_PORT}"
    volumes:
      - ./web/data:/workspace/data
      - ./web/logs:/workspace/logs
    environment:
      - NODE_ENV=production

  daemon:
    container_name: mcsmanager-daemon
    build: ./daemon
    ports:
      - "24444:${DEAMON_PORT}"
    volumes:
      - ./daemon/data:/workspace/data
      - ./daemon/logs:/workspace/logs
      - 需要映射到的本地路径:Linux路径
      - 如果还需要可以再加:和实例路径中一致
    environment:
      - NODE_ENV=production
```
Dockerfile in Web
```
FROM node:14-alpine

RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g' /etc/apk/repositories; \
    apk add docker-cli; \
    apk add git;

RUN cd /; \
    git clone https://github.com/MCSManager/MCSManager-Web-Production.git; \ #或者把github改成gitee
    mv MCSManager-Web-Production workspace; \
    cd /workspace; \
    npm install;

EXPOSE 23333

WORKDIR /workspace

CMD node app.js
```
Dockerfile in daemon
```
FROM node:14-alpine

RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g' /etc/apk/repositories; \
    apk add docker-cli; \
    apk add git;

RUN cd /; \
    git clone https://github.com/MCSManager/MCSManager-Daemon-Production.git; \
    mv MCSManager-Daemon-Production workspace; \
    cd /workspace; \
    npm install;

EXPOSE 24444

WORKDIR /workspace

CMD node app.js
```
