### ISSUE TITLE
[Feature Request] 允许自制配置文件页面

### ISSUE THREAD

**Issue by ZSXB2468** [MCSManager/MCSManager#713]
## **面板版本**
面板版本：9.5.0
对应守护进程版本：1.6.0

## **想法/建议**
很多服务器模组都有一个的配置文件，如果开放接口让模组开发者或社区维护者制作配置页并添加到配置列表组里，可以方便管理这些配置。

1、建立配置文件用的***组件库***（例如组，输入框，开关，弹窗等）及基础***模板***（自适应模板等）及简单的***文档***（组件的表示方法等），方便制作。
2、支持多种配置文件的格式，且页面设计与描述翻译***分离***。一个文件是页面设计文件，一个是设置项与表述及翻译的对应（也就是语言文件）。
3、可以自动扫描存档中已有的配置文件页面，也可以让用户自行导入。

_p.s.首先，我想象中的配置页面并不是像现在的一项项配置单纯的翻译，而是让有关联的设置放在一起，成为一个设置面板。_

## **您认为这个想法/建议在每100人中会有多少人遇到/使用**
制作40人，使用95人。

**Comment by ZSXB2468** [comment]
## 其实我想发 Feature Request😅

**Comment by unitwk** [comment]
你可以自己写，然后向我们提交 PR。

https://github.com/MCSManager/MCSManager/issues/626

**Comment by ZSXB2468** [comment]
我的意思是添加多种类型的数据，以不同的方式显示出来，并且配置项可以分组，例如下图。😄
![image](https://user-images.githubusercontent.com/62994932/186406081-bb10599b-0b16-48de-b115-1df884deb4ae.png)

**Comment by huangsijun17** [comment]
你这样非常大的一个问题是兼容性欠佳。
MC的配置文件随着MC版本更新和MOD的安装，是很可能会出现现有键值外的其他键值，导致网页配置的不兼容。

**Comment by ZSXB2468** [comment]
可以将意外的键值直接列出。

而且我只不过想让设置项分组，bool类型可以使用复选框的方式展示，下拉列表也可以提供一个例外项让用户自己输入。

**Comment by huangsijun17** [comment]
> 可以将意外的键值直接列出。
> 
> 而且我只不过想让设置项分组，bool类型可以使用复选框的方式展示，下拉列表也可以提供一个例外项让用户自己输入。

不是别设置为意外的键值，会遇到而是可以设置成网页限制外的键值。甚至可能会先某些原有是bool类型类的，变成了string类。

**Comment by zijiren233** [comment]
设置项本身属性和格式都不可控，这个Feature难度大且不可控性高

**Comment by KagurazakaNyaa** [comment]
其实我觉得可以考虑定义一套配置文件规范的说明，就像各种代理的订阅
比方说用户可以添加一个服务器类型，它从 `https://example.org/minecraft/base.spec.yaml` 加载配置文件规范订阅，里面的内容类似

```yaml
specVersion: configspec/v1beta1
specName: 基本文件规范
specContent:
  - filename: server.properties
    describe: Minecraft基本配置
    type: properties
    content:
      - key: gamemode
        type: enum
        default: survival
        range:
          - survival
          - creative
          - ......
      - key: enable-command-block
        type: boolean
        default: false
      - key: server-port
        type: integer
        range:
          min: 1
          max: 65535
      - key: motd
        type: string
        allowRegex: '.+'
    ......
  - filename: ops.json
    ......
......
```

这种写法，然后每次就把这些订阅的内容加载成各种类型的配置文件规范，这样来允许自定义配置文件规范
