### ISSUE TITLE
提议：增加一些触发备份运行的手段，如：计划任务追加系统指令（默认管理员可用）

### ISSUE THREAD

**Issue by Mr-Ao-Dragon** [MCSManager/MCSManager#896]
提议：增加一些触发备份运行的手段，如：计划任务追加系统指令（默认管理员可用）
如题，这样就可以用类似btrfs subvol snapshot 的命令直接完成备份和自动化上传，也不会超出面板的职权范围，并且该功能可用于：清理系统缓存，触发ystemd任务等。。。
_Originally posted by @Mr-Ao-Dragon in https://github.com/MCSManager/MCSManager/issues/843#issuecomment-1499622475_

**Comment by huangsijun17** [comment]
一般情况下，Minecraft的地图等被认为是不适合热备份的，除非使用服务端插件。

**Comment by Mr-Ao-Dragon** [comment]
> 一般情况下，Minecraft的地图等被认为是不适合热备份的，除非使用服务端插件。

是的，但触发系统指令能干的事情远不止这些，比如：发出http请求，清理缓存等
你说的无法热备确实是很值得思考，我的想法是将计划任务拆分成前执行 执行 后执行，比如在我的系统环境里重启服务端（只是一个示例）就可以这样设置：
- 关闭服务端前执行控制台：save-all
- 关闭服务端后执行系统命令：btrfs subvol snapshot create world/ /mnt/backup/someserver/snapshot/`date “%Y-%m-%d——%H:%M:%S”`
- 打开服务端之前执行系统命令：sudo sync && sudo echo 3 > /proc/sys/vm/drop_caches
这种自动化方案完全没有超出 mcsm 的责任涵盖，只是对计划任务增加了一些小功能，是可以接受的改动

**Comment by Bluemangoo** [comment]
是个好想法。但是对用户来说操作有点复杂。

要选择 at(start server|...), on(before|after), type(console|bash|...), script(...)

有一种Windows的美感。

_让我看看是谁又在Windows里面加答辩了？哦，是微软。那没事了。_

**Comment by Bluemangoo** [comment]
要不激进点做个注入系统吧（雾）

**Comment by Mr-Ao-Dragon** [comment]
另外无法热备的问题可以通过一个插件在 save-all 后停止写盘，暂时缓存到内存中几秒完成，或者使用更 CoW 的方法。
但这不属于讨论范围和 mcsm 职责范围，所以忽略。

**Comment by Bluemangoo** [comment]
> 另外无法热备的问题可以通过一个插件在 save-all 后停止写盘，暂时缓存到内存中几秒完成，或者使用更 CoW 的方法。
> 但这不属于讨论范围和 mcsm 职责范围，所以忽略。

u need mcdr.

**Comment by Bluemangoo** [comment]
您是否在找：
```text
./.mcsm/workflow.yaml
```

😇

**Comment by Mr-Ao-Dragon** [comment]
> 您是否在找：
> 
> ```
> ./.mcsm/workflow.yaml
> ```
> 
> innocent

好的，我看看wiki怎么写

**Comment by Mr-Ao-Dragon** [comment]
> 是个好想法。但是对用户来说操作有点复杂。
> 
> 要选择 at(start server|...), on(before|after), type(console|bash|...), script(...)
> 
> 有一种Windows的美感。
> 
> _让我看看是谁又在Windows里面加答辩了？哦，是微软。那没事了。_

更像是systemd文件

**Comment by Bluemangoo** [comment]
更激进一点。
```yaml
name: backup

on:
  after: ["server_end"]
  schedule: 
    - cron: '0 0 1 * * ?'

jobs:
  - name: auto_save
    type: console
    script: "save-all"
  - name: stop_auto_save
    type: console
    script: "save-off"
  - name: backup
    type: bash
    script: "git add .&git commit \"✨Auto backup\""
  - name: start_auto_save
    type: console
    script: "save-on"
```

槽点很多自己找找。
