### ISSUE TITLE
Linux docker compose下訪問物理機外部資料夾

### ISSUE THREAD

**Issue by kazma258** [MCSManager/MCSManager#960]
> OS: Linux Ubuntu
> 按官方教學部屬docker compsoe
> mcsm version: 面板版本 9.9.0, 对应远程节点版本 3.4.0

請問如何將實例配置中的**"工作目錄"**配置到物理機下的/mnt/Minecraft目錄?確定資料夾路徑是存在的
初學docker不太了解volumes的作法
![image](https://github.com/MCSManager/MCSManager/assets/52396503/043d1fbf-b770-449f-b686-d45ccfb57ed6)

**Comment by Mr-Ao-Dragon** [comment]
以Docker启动实例然后按照一般流程映射

**Comment by kazma258** [comment]
一般的方法是指寫在docker compose內嗎?
```yml
version: "3"
services:
    mcsm-web:
        container_name: mcsm-web
        build:
            context: .
            dockerfile: dockerfile-web
            args:
                INSTALL_PATH: ${INSTALL_PATH-/opt/docker-mcsm}
                TZ: ${TZ-Asia/Shanghai}
        network_mode: "host"
        restart: always
        environment:
            - PUID=0
            - PGID=0
            - UMASK=022
        volumes:
            - ${INSTALL_PATH-/opt/docker-mcsm}/releases/web/data:${INSTALL_PATH-/opt/docker-mcsm}/releases/web/data
            - ${INSTALL_PATH-/opt/docker-mcsm}/releases/web/logs:${INSTALL_PATH-/opt/docker-mcsm}/releases/web/logs
            - ${INSTALL_PATH-/opt/docker-mcsm}/releases/daemon/data/Config:${INSTALL_PATH-/opt/docker-mcsm}/releases/daemon/data/Config:ro
            - /mnt/Backup/:${INSTALL_PATH-/opt/docker-mcsm}/mnt/Backup #自訂路徑
    mcsm-daemon:
        container_name: mcsm-daemon
        build:
            context: .
            dockerfile: dockerfile-daemon
            args:
                INSTALL_PATH: ${INSTALL_PATH-/opt/docker-mcsm}
                TZ: ${TZ-Asia/Shanghai}
        network_mode: "host"
        restart: always
        environment:
            - PUID=0
            - PGID=0
            - UMASK=022
        volumes:
            - ${INSTALL_PATH-/opt/docker-mcsm}/releases/daemon/data:${INSTALL_PATH-/opt/docker-mcsm}/releases/daemon/data
            - ${INSTALL_PATH-/opt/docker-mcsm}/releases/daemon/logs:${INSTALL_PATH-/opt/docker-mcsm}/releases/daemon/logs
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - /mnt/Backup/:${INSTALL_PATH-/opt/docker-mcsm}/mnt/Backup #自訂路徑
```
